"""add teams, matches, scorers

Revision ID: 39d332fe9c4d
Revises: 4ba8194045c7
Create Date: 2026-05-13 19:47:59.898072

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "39d332fe9c4d"
down_revision: str | None = "4ba8194045c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("matchday", sa.Integer(), nullable=True),
        sa.Column("utc_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scorers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("player_name", sa.String(length=100), nullable=False),
        sa.Column("photo_url", sa.String(length=500), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("goals", sa.Integer(), nullable=False),
        sa.Column("season", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scorers_player_name"), "scorers", ["player_name"], unique=False)
    op.add_column("teams", sa.Column("tla", sa.String(length=8), nullable=True))
    op.add_column("teams", sa.Column("crest_url", sa.String(length=500), nullable=True))
    op.alter_column(
        "teams",
        "short_name",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.alter_column(
        "teams",
        "short_name",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.drop_column("teams", "crest_url")
    op.drop_column("teams", "tla")
    op.drop_index(op.f("ix_scorers_player_name"), table_name="scorers")
    op.drop_table("scorers")
    op.drop_table("matches")
    # ### end Alembic commands ###
