"""competition code: nullable, drop unique

Revision ID: 4ba8194045c7
Revises: 8204e9e24f4d
Create Date: 2026-05-13 18:34:53.777089

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4ba8194045c7"
down_revision: str | None = "8204e9e24f4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("competitions", "code", existing_type=sa.VARCHAR(length=10), nullable=True)
    op.drop_index(op.f("ix_competitions_code"), table_name="competitions")
    op.create_index(op.f("ix_competitions_code"), "competitions", ["code"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_competitions_code"), table_name="competitions")
    op.create_index(op.f("ix_competitions_code"), "competitions", ["code"], unique=True)
    op.alter_column("competitions", "code", existing_type=sa.VARCHAR(length=10), nullable=False)
    # ### end Alembic commands ###
