"""fdo schema: teams, matches with fdo ids, goals, bookings, standings, scorers

Revision ID: e42cdcc6b601
Revises: 39d332fe9c4d
Create Date: 2026-05-13 22:23:05.156236

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e42cdcc6b601"
down_revision: str | None = "39d332fe9c4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=True),
        sa.Column("tla", sa.String(length=8), nullable=True),
        sa.Column("crest_url", sa.String(length=500), nullable=True),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("matchday", sa.Integer(), nullable=True),
        sa.Column("utc_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("winner", sa.String(length=20), nullable=True),
        sa.Column("venue", sa.String(length=120), nullable=True),
        sa.Column("referee", sa.String(length=120), nullable=True),
        sa.Column("detail_fetched", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scorers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("player_name", sa.String(length=100), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("goals", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=True),
        sa.Column("penalties", sa.Integer(), nullable=True),
        sa.Column("matches_played", sa.Integer(), nullable=True),
        sa.Column("season", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scorers_player_name"), "scorers", ["player_name"], unique=False)
    op.create_table(
        "standings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("played", sa.Integer(), nullable=False),
        sa.Column("won", sa.Integer(), nullable=False),
        sa.Column("drawn", sa.Integer(), nullable=False),
        sa.Column("lost", sa.Integer(), nullable=False),
        sa.Column("goals_for", sa.Integer(), nullable=False),
        sa.Column("goals_against", sa.Integer(), nullable=False),
        sa.Column("goal_difference", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("form", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("minute", sa.Integer(), nullable=True),
        sa.Column("player_name", sa.String(length=100), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("card", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("minute", sa.Integer(), nullable=True),
        sa.Column("injury_time", sa.Integer(), nullable=True),
        sa.Column("player_name", sa.String(length=100), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("goal_type", sa.String(length=20), nullable=True),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("competitions", sa.Column("emblem_url", sa.String(length=500), nullable=True))
    op.add_column("competitions", sa.Column("current_matchday", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("competitions", "current_matchday")
    op.drop_column("competitions", "emblem_url")
    op.drop_table("goals")
    op.drop_table("bookings")
    op.drop_table("standings")
    op.drop_index(op.f("ix_scorers_player_name"), table_name="scorers")
    op.drop_table("scorers")
    op.drop_table("matches")
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
